# SDP-K1 + AD5592R Demo Project
# Simple initialization and ADC/DAC example

PLATFORM = stm32
TARGET = stm32f469xx

# Override NO-OS path since project is in bindings_poc/ subdirectory
NO-OS = $(realpath ../../..)

include ../../../tools/scripts/generic_variables.mk

include src.mk

include ../../../tools/scripts/generic.mk
