# APARD32690 + ADXL355 Demo Project
# Simple initialization example

PLATFORM = maxim
TARGET = max32690

# Override NO-OS path since project is in bindings_poc/ subdirectory
NO-OS = $(realpath ../../..)

include ../../../tools/scripts/generic_variables.mk

include src.mk

include ../../../tools/scripts/generic.mk
