import * as YAML from "yaml";
import {
  ParsedStruct,
  ParsedUnion,
  ParsedEnum,
  ParsedField,
  SchemaIndex,
  PRIMITIVE_TYPES,
} from "./types";
import { resolveInclude, generateSchemaId, ResolveContext } from "./resolver";

interface GenerateResult {
  yaml: string;
  warnings: string[];
}

export interface GenerateContext {
  headerPath: string;
  schemasPath: string;
  noosRoot: string;
}

function generateFieldSchema(
  field: ParsedField,
  schemaIndex: SchemaIndex,
  context: GenerateContext
): { schema: Record<string, unknown>; warning: string | null } {
  const result: Record<string, unknown> = {};
  let warning: string | null = null;

  const resolveCtx: ResolveContext = {
    headerPath: context.headerPath,
    schemasPath: context.schemasPath,
    noosRoot: context.noosRoot,
  };

  if (field.isArray) {
    result.type = "array";
    result.size = field.arraySize;

    if (PRIMITIVE_TYPES.has(field.type)) {
      result.element = { type: field.type };
    } else {
      const resolved = resolveInclude(field.type, schemaIndex, field.isUnion, resolveCtx);
      if (resolved.includePath) {
        result.element = { include: resolved.includePath };
      } else {
        result.element = { type: field.type };
      }
      warning = resolved.warning;
    }
  } else if (PRIMITIVE_TYPES.has(field.type)) {
    result.type = field.type;
  } else {
    const resolved = resolveInclude(field.type, schemaIndex, field.isUnion, resolveCtx);
    if (resolved.includePath) {
      result.include = resolved.includePath;
    } else {
      result.type = field.type;
    }
    warning = resolved.warning;
  }

  if (field.isPointer && !field.isArray) {
    result.pointer = true;
  }

  result.description = field.description || "TODO: add description";

  return { schema: result, warning };
}

export function generateStructSchema(
  struct: ParsedStruct,
  context: GenerateContext,
  schemaIndex: SchemaIndex,
  schemaDir: string | null
): GenerateResult {
  const warnings: string[] = [];
  const schemaId = generateSchemaId(struct.name, "struct", context.headerPath, schemaDir);

  const doc: Record<string, unknown> = {
    $id: schemaId,
    $type: "struct",
    $name: struct.name,
    $description: struct.description || "TODO: add description",
    $sources: {
      headers: [context.headerPath],
    },
  };

  for (const field of struct.fields) {
    const { schema, warning } = generateFieldSchema(field, schemaIndex, context);
    doc[field.name] = schema;
    if (warning) {
      warnings.push(warning);
    }
  }

  const yamlDoc = new YAML.Document(doc);
  yamlDoc.commentBefore = " Auto-generated by struct2yaml - review and adjust as needed";

  return {
    yaml: yamlDoc.toString(),
    warnings,
  };
}

export function generateUnionSchema(
  union: ParsedUnion,
  context: GenerateContext,
  schemaIndex: SchemaIndex,
  schemaDir: string | null
): GenerateResult {
  const warnings: string[] = [];
  const schemaId = generateSchemaId(union.name, "union", context.headerPath, schemaDir);

  const doc: Record<string, unknown> = {
    $id: schemaId,
    $type: "union",
    $name: union.name,
    $description: union.description || "TODO: add description",
    $sources: {
      headers: [context.headerPath],
    },
  };

  const fieldNames: string[] = [];
  for (const field of union.fields) {
    const { schema, warning } = generateFieldSchema(field, schemaIndex, context);
    doc[field.name] = schema;
    fieldNames.push(field.name);
    if (warning) {
      warnings.push(warning);
    }
  }

  if (fieldNames.length > 1) {
    doc.$override = [{ $mutex: fieldNames }];
  }

  const yamlDoc = new YAML.Document(doc);
  yamlDoc.commentBefore = " Auto-generated by struct2yaml - review and adjust as needed";

  return {
    yaml: yamlDoc.toString(),
    warnings,
  };
}

export function generateEnumSchema(
  enumDef: ParsedEnum,
  headerPath: string,
  schemaDir: string | null
): GenerateResult {
  const schemaId = generateSchemaId(enumDef.name, "enum", headerPath, schemaDir);

  const values: Record<string, { description: string }> = {};
  for (const val of enumDef.values) {
    values[val.name] = {
      description: val.description || "TODO: add description",
    };
  }

  const doc: Record<string, unknown> = {
    $id: schemaId,
    $type: "enum",
    $name: enumDef.name,
    $description: enumDef.description || "TODO: add description",
    $sources: {
      headers: [headerPath],
    },
    values,
  };

  if (enumDef.values.length > 0) {
    doc.default = enumDef.values[0].name;
  }

  const yamlDoc = new YAML.Document(doc);
  yamlDoc.commentBefore = " Auto-generated by struct2yaml - review and adjust as needed";

  return {
    yaml: yamlDoc.toString(),
    warnings: [],
  };
}
