# APARD32690 + ADXL355 Demo Project
# Simple initialization example

PLATFORM = maxim
TARGET = max32690

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
